Mosaic.Client/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using IdentityModel.Client;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;

namespace Mosaic.Client.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IHttpClientFactory HttpClientFactory;

        public AuthenticationController(IHttpClientFactory httpClientFactory)
        {
            HttpClientFactory = httpClientFactory ??
                throw new ArgumentNullException(nameof(httpClientFactory));
        }
        public async Task Logout()
        {
            var client = HttpClientFactory.CreateClient("IdPClient");

            var discoveryResponse = await client.GetDiscoveryDocumentAsync();
            if (discoveryResponse.IsError)
            {
                throw new Exception(discoveryResponse.Error);
            }

            // Revoke refresh token
            var accessTokenRevocationResponse = await client.RevokeTokenAsync(
            new TokenRevocationRequest
                {
                    Address = discoveryResponse.RevocationEndpoint,
                    ClientId = "mosaicclient",
                    ClientSecret = "secret",
                    Token = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken)
                });

            if (accessTokenRevocationResponse.IsError)
            {
                throw new Exception(accessTokenRevocationResponse.Error);
            }

            // Revoke refresh token
            var refreshokenRevocationResponse = await client.RevokeTokenAsync(
                new TokenRevocationRequest
                {
                    Address = discoveryResponse.RevocationEndpoint,
                    ClientId = "mosaicclient",
                    ClientSecret = "secret",
                    Token = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.RefreshToken)
                });

            if (refreshokenRevocationResponse.IsError)
            {
                throw new Exception(refreshokenRevocationResponse.Error);
            }

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
        }
    }
}

Mosaic.Client/Controllers/StockController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mosaic.Client.Services;

namespace Mosaic.Client.Controllers
{
    public class StockController : Controller
    {
        private readonly IStockService StockService;
        private readonly ILogger<StockController> logger;

        public StockController(IStockService _StockService, ILogger<StockController> _logger)
        {
            StockService = _StockService;
            logger = _logger ?? throw new ArgumentNullException(nameof(_logger));
        }
        public IActionResult Index()
        {
            try
            {
                return View(StockService.GetAllStocks().Result);
            }
            catch(Exception e)
            {
                logger.LogError($"Error happened with message {e.Message} and inner exception {e.InnerException.Message}");
                return RedirectToAction("AccessDenied", "Authorisation");
            }
        }

        public IActionResult GetFinnHubStock()
        {
            try
            {
                return View(StockService.GetFinnHubStock().Result);
            }
            catch
            {
                return RedirectToAction("AccessDenied", "Authorisation");
            }

        }
        public IActionResult GetUserStocks()
        {
            try
            {
                var userId = User.Claims.FirstOrDefault(c => c.Type == "sub")?.Value;
                return View(StockService.GetUserStocks(userId).Result);
            }
            catch(Exception e)
            {
                logger.LogError($"error thrown with exception {e.Message} and inner exception {e.InnerException.Message}");
                return RedirectToAction("AccessDenied", "Authorisation");
            }

        }
    }
}

Mosaic.Client/Controllers/UserController.cs
using IdentityModel.Client;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Mosaic.Client.ViewModels;
using System;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Mosaic.Client.Controllers
{
    public class UserController : Controller
    {
        private readonly IHttpClientFactory HttpClientFactory;
        private readonly User User;

        public UserController(IHttpClientFactory httpClientFactory)
        {
            HttpClientFactory = httpClientFactory ??
                throw new ArgumentNullException(nameof(httpClientFactory));
            User = new User();
        }


        public async Task<IActionResult> MyDetails()
        {
            var idpClient = HttpClientFactory.CreateClient("IdPClient");
            
            // Get the .wellKnownDocument which includes all endpoints of the IdP
            var metaDataResponse = await idpClient.GetDiscoveryDocumentAsync();

            if (metaDataResponse.IsError)
            {
                throw new Exception(
                    "Problem accessing the discovery endpoint"
                    , metaDataResponse.Exception);
            }

            var accessToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);

            var userInfoResponse = await idpClient.GetUserInfoAsync(
                new UserInfoRequest
                {
                    Address = metaDataResponse.UserInfoEndpoint,
                    Token = accessToken
                });

            if (userInfoResponse.IsError)
            {
                throw new Exception(
                    "Problem accessing the UserInfo endpoint"
                    , userInfoResponse.Exception);
            }

            var email = userInfoResponse.Claims.FirstOrDefault(c => c.Type == "email")?.Value;
            User.Email = email;

            return View(User);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Admin()
        {
            return View();
        }
    }
}

Mosaic.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mosaic.Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mosaic.Client</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stock" asp-action="Index">Stocks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stock" asp-action="GetFinnHubStock">FinnHub-Stock</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Admin">Admin</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Stock" asp-action="GetUserStocks">MyStocks</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="MyDetails">MyDetails</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Mosaic.Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>